import OAI.NumberTheory.DirichletL.Detector.ArbitraryTotalSourceBatch
import OAI.NumberTheory.DirichletL.Detector.ActualSourceBatchTotal
import OAI.NumberTheory.DirichletL.Moments.FiberPositiveAtLowKappa
import OAI.NumberTheory.DirichletL.Energy.FiniteLabelPositiveAtLowKappa
import OAI.NumberTheory.DirichletL.Moments.MarkedHeightBudgetLowKappa
