import UpstreamNano_20261009_155046
set_option pp.universes true
set_option pp.fullNames true
set_option pp.explicit true
set_option pp.all true
set_option pp.maxSteps 1000000

set_option pp.universes true
#check @OAI.SevenEighths.FixedRadialRowDomination.exists_fixed_radial_positiveRow_domination
set_option pp.universes false
#print axioms OAI.SevenEighths.FixedRadialRowDomination.exists_fixed_radial_positiveRow_domination
set_option pp.universes true
#check @OAI.SevenEighths.FiniteFamilyNonexceptional.fixed_inducing_free_norm_le
set_option pp.universes false
#print axioms OAI.SevenEighths.FiniteFamilyNonexceptional.fixed_inducing_free_norm_le
set_option pp.universes true
#check @OAI.SevenEighths.FiniteFamilyNonexceptional.eventually_finite_family_no_fixed_inducing
set_option pp.universes false
#print axioms OAI.SevenEighths.FiniteFamilyNonexceptional.eventually_finite_family_no_fixed_inducing
