import UpstreamNano_20261009_220116
set_option pp.universes true
set_option pp.fullNames true
set_option pp.explicit true
set_option pp.all true
set_option pp.maxSteps 1000000

set_option pp.universes true
#check @OAI.SevenEighths.SourcePlainMarkedUniversalLowKappa.exists_source_slots_and_universal_plain_marked
set_option pp.universes false
#print axioms OAI.SevenEighths.SourcePlainMarkedUniversalLowKappa.exists_source_slots_and_universal_plain_marked
set_option pp.universes true
#check @OAI.SevenEighths.PlainUnmarkedAdmissionLowKappa.actual_growth_absorption_principal_exponent
set_option pp.universes false
#print axioms OAI.SevenEighths.PlainUnmarkedAdmissionLowKappa.actual_growth_absorption_principal_exponent
set_option pp.universes true
#check @OAI.SevenEighths.PlainUnmarkedAdmissionLowKappa.actual_plain_unmarked_admission
set_option pp.universes false
#print axioms OAI.SevenEighths.PlainUnmarkedAdmissionLowKappa.actual_plain_unmarked_admission
