import OAI.NumberTheory.DirichletL.Detector.GlobalRegionLowKappa
import OAI.NumberTheory.DirichletL.Detector.GlobalCorrectionLowKappa
import OAI.NumberTheory.DirichletL.Detector.GlobalSourceCorrectionExistenceLowKappa
import OAI.NumberTheory.DirichletL.Hecke.DirichletLowKappa
import OAI.NumberTheory.DirichletL.PrincipalSlotEstimateLowKappa
import OAI.NumberTheory.DirichletL.PrincipalSignalComparisonLowKappa
import OAI.NumberTheory.DirichletL.Moments.RayIdentityClassCoefficient
import OAI.NumberTheory.DirichletL.PrincipalSignalScalingLowKappa
