import UpstreamNano_20261009_155718
set_option pp.universes true
set_option pp.fullNames true
set_option pp.explicit true
set_option pp.all true
set_option pp.maxSteps 1000000

set_option pp.universes true
#check @OAI.SevenEighths.CenteredMomentEnergyReferenceLowBranchGeometry.length_eq_max_log
set_option pp.universes false
#print axioms OAI.SevenEighths.CenteredMomentEnergyReferenceLowBranchGeometry.length_eq_max_log
set_option pp.universes true
#check @OAI.SevenEighths.CenteredMomentEnergyReferenceLowBranchGeometry.slot_budgets
set_option pp.universes false
#print axioms OAI.SevenEighths.CenteredMomentEnergyReferenceLowBranchGeometry.slot_budgets
set_option pp.universes true
#check @OAI.SevenEighths.CenteredMomentEnergyReferenceLowBranchGeometry.reflected_low
set_option pp.universes false
#print axioms OAI.SevenEighths.CenteredMomentEnergyReferenceLowBranchGeometry.reflected_low
set_option pp.universes true
#check @OAI.SevenEighths.CenteredMomentEnergyReferenceLowBranchGeometry.deleted_reference_cases
set_option pp.universes false
#print axioms OAI.SevenEighths.CenteredMomentEnergyReferenceLowBranchGeometry.deleted_reference_cases
set_option pp.universes true
#check @OAI.SevenEighths.CenteredMomentEnergyReferenceLowBranchGeometry.reflected_low_admissible
set_option pp.universes false
#print axioms OAI.SevenEighths.CenteredMomentEnergyReferenceLowBranchGeometry.reflected_low_admissible
