import UpstreamNano_20261009_173643
set_option pp.universes true
set_option pp.fullNames true
set_option pp.explicit true
set_option pp.all true
set_option pp.maxSteps 1000000

set_option pp.universes true
#check @OAI.SevenEighths.PlainMarkedAdmissionLowKappa.actual_plain_marked_admission
set_option pp.universes false
#print axioms OAI.SevenEighths.PlainMarkedAdmissionLowKappa.actual_plain_marked_admission
set_option pp.universes true
#check @OAI.SevenEighths.UniformDegreePositiveAtLowKappa.exists_degree_before_character_positiveAt
set_option pp.universes false
#print axioms OAI.SevenEighths.UniformDegreePositiveAtLowKappa.exists_degree_before_character_positiveAt
set_option pp.universes true
#check @OAI.SevenEighths.EventualFiniteSourcePlainMarkedLowKappa.eventually_finite_source_plain_marked
set_option pp.universes false
#print axioms OAI.SevenEighths.EventualFiniteSourcePlainMarkedLowKappa.eventually_finite_source_plain_marked
