import RellichKondrachov.Analysis.FunctionalSpaces.Sobolev.Euclidean.L2Compactness.Approximation
#check @RellichKondrachov.Analysis.FunctionalSpaces.Sobolev.Euclidean.L2Compactness.instIsProbabilityMeasure_kernelMeasure
#print axioms RellichKondrachov.Analysis.FunctionalSpaces.Sobolev.Euclidean.L2Compactness.kernelMeasure
#print axioms RellichKondrachov.Analysis.FunctionalSpaces.Sobolev.Euclidean.L2Compactness.kernelMeasure_univ
#print axioms RellichKondrachov.Analysis.FunctionalSpaces.Sobolev.Euclidean.L2Compactness.instIsProbabilityMeasure_kernelMeasure
#print axioms RellichKondrachov.Analysis.FunctionalSpaces.Sobolev.Euclidean.L2Compactness.integral_kernelMeasure_eq_integral_smul
#print axioms RellichKondrachov.Analysis.FunctionalSpaces.Sobolev.Euclidean.L2Compactness.integral_kernelMeasure_eq_integral_mul
#print axioms RellichKondrachov.Analysis.FunctionalSpaces.Sobolev.Euclidean.L2Compactness.smoothFun_eq_integral_kernelMeasure
#print axioms RellichKondrachov.Analysis.FunctionalSpaces.Sobolev.Euclidean.L2Compactness.sq_integral_le_integral_sq_of_isProbabilityMeasure
#print axioms RellichKondrachov.Analysis.FunctionalSpaces.Sobolev.Euclidean.L2Compactness.norm_sq_translateL2_sub_extendByZeroL2_eq_integral_sq
#print axioms RellichKondrachov.Analysis.FunctionalSpaces.Sobolev.Euclidean.L2Compactness.smoothFun_sub_extendByZeroFun_sq_le_integral_sq
#print axioms RellichKondrachov.Analysis.FunctionalSpaces.Sobolev.Euclidean.L2Compactness.norm_sq_smoothL2_sub_extendByZeroL2_le_integral_norm_sq_translateL2_sub_extendByZeroL2
