import OAI.NumberTheory.DirichletL.Detector.GlobalRegionLowKappa
import OAI.NumberTheory.DirichletL.Detector.GlobalCorrectionLowKappa
import OAI.NumberTheory.DirichletL.Detector.GlobalSourceCorrectionExistenceLowKappa
